## Configuracion de Spring
spring:
  application:
    name: ms-library-books

## Configuracion de Instancia 
server:
  port: 8088
  fullAddress: ${HOST:http://localhost}:${PORT:${server.port}}

## Configuracion del cliente de Eureka
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    hostname: ms-library-books

##Elasticsearch config
elasticsearch:
  host: ${ELASTICSEARCH_HOST:bookshop-2820918303.eu-central-1.bonsaisearch.net}
  credentials:
    user: ${ELASTICSEARCH_USER:54dgcrp6xi}
    password: ${ELASTICSEARCH_PWD:wc721gfufq}
logging:
  level:
    tracer: TRACE